const ready=!!(window.SUPABASE_URL&&window.SUPABASE_KEY);const sb=ready?supabase.createClient(window.SUPABASE_URL,window.SUPABASE_KEY):null;const $=x=>document.getElementById(x);let user,profile;
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));const uid=x=>String(x||"").trim().toUpperCase().replace(/\s+/g,"");
function toast(x){$("toast").textContent=x;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2200)}
function screen(x){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(x).classList.add("active");document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.s==x));if(x=="app")recent();if(x=="vehicles")vehicles();if(x=="logs")logs()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>screen(b.dataset.s));
function logged(on){$("login").classList.toggle("active",!on);$("app").classList.toggle("active",on);$("nav").classList.toggle("hidden",!on);$("logout").classList.toggle("hidden",!on);$("notice").classList.toggle("hidden",on)}
async function start(){if(!ready){$("login").classList.add("active");return}let s=(await sb.auth.getSession()).data.session;if(s)after(s.user);else $("login").classList.add("active")}
async function after(u){user=u;let r=await sb.from("profiles").select("*").eq("id",u.id).single();if(r.error){$("msg").textContent="Falta crear el perfil del usuario en profiles.";return}profile=r.data;$("userInfo").textContent=profile.nombre+" · "+profile.rol;$("role").textContent="Rol: "+profile.rol;logged(true);screen("app")}
$("loginBtn").onclick=async()=>{let r=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(r.error)$("msg").textContent=r.error.message;else after(r.data.user)};
$("logout").onclick=async()=>{await sb.auth.signOut();location.reload()};
async function access(chip){chip=uid(chip);if(!chip)return;let r=await sb.rpc("registrar_acceso",{p_chip_uid:chip,p_sentido:"entrada"});if(r.error){toast(r.error.message);return}let v=r.data;$("result").className="result "+(v.resultado=="AUTORIZADO"?"ok":"no");$("result").innerHTML=(v.resultado=="AUTORIZADO"?"🟢 <b>ACCESO AUTORIZADO</b>":"🔴 <b>ACCESO DENEGADO</b>")+"<br><br>"+(v.placa?`Placa: <b>${esc(v.placa)}</b><br>Apartamento: ${esc(v.apto)}<br>Residente: ${esc(v.residente)}<br><br>`:"Chip no registrado o bloqueado.")+(v.resultado=="AUTORIZADO"?"✓ Levantar talanquera manualmente.":"No permitir ingreso.");recent()}
$("scan").onclick=async()=>{if(!("NDEF" in window)){toast("Este Android no ofrece Web NFC. Usaremos app Android nativa si es necesario.");return}try{let n=new NDEFReader();await n.scan();toast("Acerca el chip");n.onreading=e=>access(e.serialNumber)}catch(e){toast(e.message)}};
$("manual").onclick=()=>{let x=prompt("UID del chip");if(x)access(x)};
$("vf").onsubmit=async e=>{e.preventDefault();if(profile.rol!="admin"){toast("Solo administrador");return}let r=await sb.from("vehicles").insert({conjunto_id:profile.conjunto_id,apto:$("apto").value.trim(),residente:$("resident").value.trim(),placa:$("plate").value.trim().toUpperCase(),marca_modelo:$("model").value.trim(),color:$("color").value.trim(),chip_uid:uid($("uid").value),estado:$("status").value});if(r.error)toast(r.error.message);else{e.target.reset();toast("Vehículo guardado");vehicles()}};
$("search").oninput=vehicles;
async function vehicles(){if(!profile)return;let q=$("search").value.trim(),z=sb.from("vehicles").select("*").eq("conjunto_id",profile.conjunto_id).order("apto");if(q)z=z.or(`placa.ilike.%${q}%,apto.ilike.%${q}%,residente.ilike.%${q}%`);let r=await z;$("vlist").innerHTML=(r.data||[]).map(v=>`<div class="item"><b>${esc(v.placa)}</b> · Apto ${esc(v.apto)}<br>${esc(v.residente)} · ${esc(v.marca_modelo)}<br><small>NFC: ${esc(v.chip_uid)} · ${esc(v.estado)}</small></div>`).join("")||"<p>No hay vehículos.</p>"}
async function logs(){let r=await sb.from("access_logs").select("*").eq("conjunto_id",profile.conjunto_id).order("fecha_hora",{ascending:false}).limit(100);$("llist").innerHTML=(r.data||[]).map(x=>`<div class="item"><b>${esc(x.placa||"Sin placa")}</b> · ${esc(x.resultado)}<br><small>${new Date(x.fecha_hora).toLocaleString("es-CO")}</small></div>`).join("")||"<p>Sin registros.</p>"}
async function recent(){let r=await sb.from("access_logs").select("*").eq("conjunto_id",profile.conjunto_id).order("fecha_hora",{ascending:false}).limit(8);$("recent").innerHTML=(r.data||[]).map(x=>`<div class="item"><b>${esc(x.placa||"Sin placa")}</b> · ${esc(x.resultado)}<br><small>${new Date(x.fecha_hora).toLocaleString("es-CO")}</small></div>`).join("")||"<p>Sin accesos.</p>"}
$("csv").onclick=async()=>{let r=await sb.from("access_logs").select("*").eq("conjunto_id",profile.conjunto_id).order("fecha_hora",{ascending:false});let rows=[["Fecha","Hora","Placa","Apto","NFC","Resultado","Sentido"],...(r.data||[]).map(x=>{let d=new Date(x.fecha_hora);return[d.toLocaleDateString("es-CO"),d.toLocaleTimeString("es-CO"),x.placa||"",x.apto||"",x.chip_uid,x.resultado,x.sentido]})];let c=rows.map(a=>a.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+c],{type:"text/csv"}));a.download="historial_terragrata.csv";a.click()};
start();